# Generated by Django 2.2.7 on 2020-03-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2000', 2000), ('2001', 2001), ('2002', 2002)], default='Select a Year', max_length=7)),
                ('courseComplete', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='details.subjects')),
                ('teachername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.teacherDetails')),
                ('teachesSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.semester')),
            ],
        ),
    ]
