# Generated by Django 2.2.7 on 2020-01-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.program')),
                ('teachername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.teacherDetails')),
                ('teachesSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.semester')),
                ('teachesSubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subjects')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.year')),
            ],
        ),
    ]
