# Generated by Django 2.2.7 on 2020-01-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='teacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(default='None', max_length=30)),
                ('teachesSemester', models.IntegerField(blank=True, default='None', max_length=30)),
                ('Paymentby', models.CharField(blank=True, default='None', max_length=30)),
                ('teachesSubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subjects')),
            ],
        ),
    ]
