# Generated by Django 2.2.7 on 2020-01-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdetails',
            name='Paymentby',
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='teachesSemester',
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='teachesSubjects',
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachesSemester', models.IntegerField(blank=True, default='None', max_length=30)),
                ('teachername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.teacherDetails')),
                ('teachesSubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subjects')),
            ],
        ),
    ]
