# Generated by Django 2.2.7 on 2020-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programs',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
