# Generated by Django 2.2.7 on 2020-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200127_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='year',
            field=models.CharField(choices=[('2000', 2000), ('2001', 2001), ('2002', 2002)], default='Select a Year', max_length=7),
        ),
        migrations.DeleteModel(
            name='year',
        ),
    ]
