# Generated by Django 2.2.7 on 2020-01-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200126_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachesSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.semester'),
        ),
    ]
