# Generated by Django 2.2.7 on 2020-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200127_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courseComplete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
